default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: mama-friends

development:
  <<: *default
  database: yourNeighbor_development
  host: http://10.11.38.160

test:
  <<: *default
  database: yourNeighbor_test

production:
  <<: *default
  database: yourNeighbor_production
