default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: mama-friends

development:
  <<: *default
  database: yourNeighbor
  host: http://10.11.38.160

test:
  <<: *default
  database: yourNeighbor

production:
  <<: *default
  database: yourNeighbor
  host: 127.0.0.1
