default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: passpass

development:
  <<: *default
  database: mamafriends
  host: http://54.249.109.82/

test:
  <<: *default
  database: mamafriends

production:
  <<: *default
  database: mamafriends
  host: 127.0.0.1
