default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: [username]
  password: [password]

development:
  <<: *default
  database: yourNeighbor_development

test:
  <<: *default
  database: yourNeighbor_test

production:
  <<: *default
  database: yourNeighbor_production
